server:
  port: 7070
  contextPath: /authserver

jwt:
  certificate:
    store:
      file: classpath:/certificate/sayan.jks
      password: sayan
    key:
      alias: myauthkey
      password: sayan

spring:
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost/viome?currentSchema=viomeauth2
    username: viome
    password: viome123

token:
  validity: 212000



#    5am every day
purge:
   cron.expression: 1 * * * * *




security:
  oauth2:
    resource:
      filter-order: 3
      jwt:
        keyValue: |
                 -----BEGIN PUBLIC KEY-----
                 MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoTOQ4uIILzJmZGumYUQo
                 UnSsRudErY9pdVdDNfZrI/wWwx+KbLv3P9rhkyU/wwAIiTINqjXmI7p5nRsqvShJ
                 huuTWUzHtkxG3lgbn1UfKDUgq87HK9W3/d7wvUVjRoqhOuj+tRTMy5NjRk+c1IoH
                 PyWCTF51axAoy4CX+iP5cJ+rQnhHlb9MLX8bXMO5l1D2a84jTp4TREjgD23i/NwB
                 PWlR4mGR1PyaQC2NgY3nDXukuxAfHQ4hgE+WaPlNS6xYh9yarS4GBaEhzjg/yFIy
                 NM4+YheC+n8i0SpQZxYRYVjSk8VScGbrh2L/Iw7fBPB1pcxJRmjCDSbEqx6RS6SM
                 DwIDAQAA
                 -----END PUBLIC KEY-----