# Make the application available at http://localhost:7070/authserver
server:
  port: 7070
  contextPath: /authserver

# Our certificate settings for enabling JWT tokens
jwt:
  certificate:
    store:
      file: classpath:/certificate/sayan.jks
      password: sayan
    key:
      alias: myauthkey
      password: sayan

      
security:
  oauth2:
    resource: 
      filter-order: 3
      