server:
  port: 8080
  contextPath: /

# Configure the Authorization Server and User Info Resource Server details
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:7070/authserver/oauth/token
      userAuthorizationUri: http://localhost:7070/authserver/oauth/authorize
      clientId: authserver
      clientSecret: passwordforauthserver
    resource:
      userInfoUri: http://localhost:7070/authserver/secured/user

person:
  url: http://localhost:9000/person

#zuul:
#  routes:
#    resource:
#      path: /api/**
#      url: http://localhost:9000
#    user:
#      path: /user/**
#      url: http://localhost:9000/user


#spring:
#  cloud:
#    gateway:
#      routes:
#        - predicates:
#            - Path=/props/**
#          uri: "http://httpbin.org"

spring:
  cloud:
    gateway:
      routes:
      - id: baeldung_route
        uri: http://localhost:9000
        predicates:
        - Path=/baeldung

# Make sure the OAuth2 token is only relayed when using the internal API,
# do not pass any authentication to the external API
proxy:
  auth:
    routes:
      api: oauth2