server:
  port: 8080
  contextPath: /

# Configure the Authorization Server and User Info Resource Server details
#security:
#  oauth2:
#    client:
#      accessTokenUri: http://localhost:7070/authserver/oauth/token
#      userAuthorizationUri: http://localhost:7070/authserver/oauth/authorize
#      clientId: vibe
#      clientSecret: passwordforvibeserver
#    resource:
#      userInfoUri: http://localhost:9000/user

person:
  url: http://localhost:9000/person

zuul:
  routes:
    resource:
      path: /api/**
      url: http://localhost:9000
    user: 
      path: /user/**
      url: http://localhost:9000/user

# Make sure the OAuth2 token is only relayed when using the internal API,
# do not pass any authentication to the external API
proxy:
  auth:
    routes:
      api: oauth2